- name: Configure as slave
  hosts: webserver
  remote_user: ubuntu
  tasks:
   - name: update
     apt:
      update_cache : yes

   - name: create Jenkins directory
     file:
      path: /home/ubuntu/jenkins
      mode : '0777'
      state: directory

   - name: install open-jdk
     apt:
      name: openjdk-8-jdk
      state: present

   - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

   - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

   - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
 

     